version: "3.8"

services:
  green_pulse_frontend:
    container_name: green_pulse_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    
    networks:
      - greenpulse_net
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:3000"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  greenpulse_net:
    external: true