import Providers from "@/components/Providers/Providers";
import "./globals.css";
;

export const metadata = {
  title: "Green Pulse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
